name: Policy Check

on:
  pull_request:
    paths:
      - 'examples/**'

jobs:
  policy-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install OPA
      run: |
        wget https://openpolicyagent.org/downloads/v0.41.0/opa_linux_amd64_static -O opa
        chmod +x opa
        sudo mv opa /usr/local/bin/

    - name: Evaluate Policies
      run: |
        ./opa eval --data opa/policies/ --input examples/service.yaml 'data.kubernetes.allow' --format pretty
      continue-on-error: true
